// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glnnqavizdetfrbscppl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsbm5xYXZpemRldGZyYnNjcHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzI4MDMsImV4cCI6MjA3MjcwODgwM30.lCULlcdm34j_1dR9tZ7KA5hzb_Rd1sIy7qasJ1zE0uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});